---

:catch:
  :color: :no

:cmock:
  :framework: :catch

:flags:
  :test:
    :compile:
      :*:
        - -std=c++17
        - -Og
    :linker:
      :*:
        - -lstdc++

# :paths:
#   :support:
#     - build/test/main

:tools:
  :test_compiler:
    :executable: g++
    :name: 'GCC Compiler'
  :test_linker:
     :executable: g++
     :name: 'GCC Linker'
  :test_includes_preprocessor:
    :executable: g++
    :name: gcc_cpp_test_includes_preprocessor
    :arguments:
      - -E
      - -MM
      - -MG
      - -std=c++17
      - -I"$": COLLECTION_PATHS_TEST_SUPPORT_SOURCE_INCLUDE_VENDOR
      - -I"$": COLLECTION_PATHS_TEST_TOOLCHAIN_INCLUDE
      - -D$: COLLECTION_DEFINES_TEST_AND_VENDOR
      - -D$: DEFINES_TEST_PREPROCESS
      - -DGNU_COMPILER
      - -w
      - "${1}"
  :test_file_preprocessor:
    :executable: g++
    :name: gcc_cpp_test_file_preprocessor
    :arguments:
      - -E
      - -std=c++17
      - -I"$": COLLECTION_PATHS_TEST_SUPPORT_SOURCE_INCLUDE_VENDOR
      - -I"$": COLLECTION_PATHS_TEST_TOOLCHAIN_INCLUDE
      - -D$: COLLECTION_DEFINES_TEST_AND_VENDOR
      - -D$: DEFINES_TEST_PREPROCESS
      - -DGNU_COMPILER
  :test_dependencies_generator:
    :executable: g++
    :name: gcc_cpp_test_dependencies_generator
    :arguments:
      - -E
      - -MM
      - -MG
      - -std=c++17
      - -I"$": COLLECTION_PATHS_TEST_SUPPORT_SOURCE_INCLUDE_VENDOR
      - -I"$": COLLECTION_PATHS_TEST_TOOLCHAIN_INCLUDE
      - -D$: COLLECTION_DEFINES_TEST_AND_VENDOR
      - -D$: DEFINES_TEST_PREPROCESS
      - -DGNU_COMPILER
      - -w

...